### ISSUE TITLE
Bill Buck Generator.  I do not see the choice of Bill or Vonette

### ISSUE THREAD

**Issue by nicholaskusiak** [CruGlobal/bill-bucks-generator#52]
I do not see the choice of Bill or Vonette.

![image](https://user-images.githubusercontent.com/10341743/139483201-1f3a14a8-80e6-42bd-b7b2-f4d680f45eb2.png)

**Comment by JasonBuckner** [comment]
@nicholaskusiak Increase the "Count" above 4 to see a Vonette. 
See also Issue #34.
