### ISSUE TITLE
Show History of Bill Bucks a user has generated

### ISSUE THREAD

**Issue by twinge** [CruGlobal/bill-bucks-generator#53]

**Comment by JasonBuckner** [comment]
Related to #7 and #31.

**Comment by abateman-ai** [comment]
I would also bump this request as something I think could be useful. :) Or at least have a history of bill bucks sent out. @dbenton9

**Comment by dbenton9** [comment]
@JasonBuckner Who needs to push this so it can get on the OKR list... someone in HR would be my guess?

**Comment by jessewinckler** [comment]
Bump. I'd like to see my history or see a checkbox to at least get an email myself of what I sent.

**Comment by mattdrees** [comment]
@dbenton9 how big of a chunk of work would this be?

**Comment by dbenton9** [comment]
Depends on what we're going for here. A confirmation email to the giver should take less than a day.  A view showing history would also hopefully be no more than a day. Calculating in unforeseen complications I'd estimate 2-4 days.

**Comment by dbenton9** [comment]
I just added a quick little patch that will automatically BCC the giver onto the sent email.
