### ISSUE TITLE
Count is incremented even if you've not sent anything

### ISSUE THREAD

**Issue by tohagan** [CruGlobal/bill-bucks-generator#55]
I generated some Bills fine.   They either weren't sent or failed to send but in both cases the count of generated bills was incremented - even before I'd logged in.

**Comment by dbenton9** [comment]
I've discovered since adding the login, the counter is no longer working properly. I'm going to be removing it until we can implement a solution.

**Comment by dbenton9** [comment]
You can follow #59, to get updates to this issue.
