### ISSUE TITLE
Can't send from affiliated organisations 

### ISSUE THREAD

**Issue by tohagan** [CruGlobal/bill-bucks-generator#56]
I attempted to send some to a Cru.org user from a non-Cru.org account (logged in via Okta) @powertochange.org.au .
This failed to send the Bills.

**Comment by JasonBuckner** [comment]
Only specific departments within Cru are participating in the Bill Bucks program (as it is paid for out of certain budgets - more info at [https://help.cru.org/bills](https://help.cru.org/bills)). 
Later today, I plan to make an adjustment (in Okta) to limit who can log in to the Bill Bucks Generator to users from those departments.
