### ISSUE TITLE
Fix Counter

### ISSUE THREAD

**Issue by dbenton9** [CruGlobal/bill-bucks-generator#59]
Since adding okta login, the counter isn't working properly and we need a new method to accurately update it.

**Comment by JasonBuckner** [comment]
@dbenton9 This one's resolved, right?

**Comment by dbenton9** [comment]
I got the work done but I've been having issues getting this deployed. One of my dependecies updated and screwed everything up... so I'm still trying to sort that out admist other OKR resposibilities 😬

**Comment by dbenton9** [comment]
@JasonBuckner Finaly fixed!
