### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by blakemurphycru** [CruGlobal/bill-bucks-generator#83]
![login error](https://user-images.githubusercontent.com/106197484/187720158-9ba5dfb9-6f31-46fd-999a-905026e1dbde.png)

**Comment by JasonBuckner** [comment]
I think I see the problem. Hang tight.

**Comment by blakemurphycru** [comment]
My dude!

**Comment by JasonBuckner** [comment]
Access to Login to send Bill Bucks is restricted. Currently, only members of _certain_ email distribution lists are allowed to use this feature. Contact help@cru.org to be sure you're added to the appropriate email distribution list.
